###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

isp-monitor-memcached:
  image: phpdockerio/memcached:latest
  container_name: isp-monitor-memcached

isp-monitor-redis:
  image: phpdockerio/redis:latest
  container_name: isp-monitor-redis

isp-monitor-webserver:
  image: phpdockerio/nginx:latest
  container_name: isp-monitor-webserver
  volumes:
      - ..:/var/www/isp-monitor
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - isp-monitor-php-fpm

isp-monitor-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: isp-monitor-php-fpm
  volumes:
    - ..:/var/www/isp-monitor
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - isp-monitor-memcached
    - isp-monitor-redis
