#php-app-memcached:
#  image: phpdockerio/memcached:latest
#  container_name: php-app-memcached

php-app-redis:
  image: phpdockerio/redis:latest
  container_name: php-app-redis

php-app-webserver:
  image: phpdockerio/nginx:latest
  container_name: php-app-webserver
  volumes:
      - ..:/var/www/php-app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - php-app-php-fpm

php-app-mongodata:
  container_name: php-app-mongodata
  image: mongo:latest
  volumes:
    - /data/db
  command: --break-mongo

php-app-mongo:
  container_name: php-app-mongo
  image: mongo:latest
  volumes_from:
    - php-app-mongodata
  ports:
    - "27018:27017"
  command: --smallfiles --rest

php-app-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: php-app-php-fpm
  volumes:
    - ..:/var/www/php-app
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    - ../tmp:/tmp
  links:
    - php-app-redis
    - php-app-mongo